on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: echo ${{ steps.release.outputs.release_created }}
  create-release-pr:
    needs: build
    runs-on: ubuntu-latest
     outputs:
      releases_created: ${{ steps.rp.outputs.releases_created }}
    steps:
      - id: rp
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: node
          package-name: release-please-action
          monorepo-tags: true
  publish-package:
    if: job.create-release-pr.outputs.releases_created
    needs: [build, create-release-pr]
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT: ${{ needs.create-release-pr.outputs.releases_created }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: echo "$OUTPUT"
      - run: echo "Success now publish"
