on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build

  create-release-pr:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.rp.outputs.releases_created }}
    steps:
      - id: rp
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: node
          package-name: release-please-action
          monorepo-tags: true
      - run: echo ${{steps.rp.outputs.releases_created}}
  publish-package:
    needs: [build, create-release-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - env:
          OUTPUT1: ${{needs.create-release-pr.outputs.output1}}
          OUTPUT2: Test
        run: echo $OUTPUT1 $OUTPUT2
      - run: echo "Success now publish"
