on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Build, Generate Release PR, and Publish

jobs:
  build:
    name: Build and Generate Release PR or Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn ci
      - name: Run Build
        run: yarn build
      - id: rp
        name: Create a Release PR or Create a Release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: node
          package-name: release-please-action
          monorepo-tags: true
      - name: Publish Packages
        if: steps.rp.outputs.releases_created
        run: yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
