on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Build, Generate Release PR, and Publish

jobs:
  build:
    name: Build and Generate Release PR or Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Run Build
        run: yarn build
      - id: rp
        name: Release Please Process (Create Release or Create Release PR)
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: node
          package-name: release-please-action
          monorepo-tags: true
      - name: Publish Packages
        if: steps.rp.outputs.releases_created
        run: npx lerna publish from-package
