name: Setup Node and install dependencies

jobs:
  prep:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn ci
