name: Setup Node and install dependencies

on: workflow_call

jobs:
  prep:
    name: Preparing build process
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn ci
