on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  checkout:
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: ssistoza/release-please-monorepo-poc
      - run: yarn install
      - run: yarn build
  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
