name: Create PR or Publish new Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Create PR or Publish new Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - id: rp
        name: Create a Release PR or Create a Release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: node
          package-name: release-please-action
          monorepo-tags: true
      - uses: ./.github/workflow/install-dependencies.yml
        if: steps.rp.outputs.releases_created
      - name: Run Build
        if: steps.rp.outputs.releases_created
        run: yarn build
      - name: Publish Packages
        if: steps.rp.outputs.releases_created
        run: yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
