name: Validate Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  validate:
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Install Dependencies
        uses: ./.github/workflows/install-dependencies.yml
      - name: Gate Checking
        run: echo Linting PR Title at this point `yarn turbo run build lint test`
