name: Validate Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  validate:
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn ci
      - name: Gate Checking
        run: yarn test
